#-----------------------------
# seven's config for starship.
#-----------------------------

# WARNING: not all color and prompt part combinations were tested. Most probably, some of these look fucked up or straight up have the wrong colors.

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:color_red)\
[ 󰣑 ](fg:color_surface0 bg:prev_fg)\
[](fg:prev_bg bg:color_maroon)\
$username\
$hostname\
[](fg:prev_bg bg:color_peach)\
$directory\
[](fg:prev_bg bg:color_yellow)\
$git_branch\
$git_commit\
$git_status\
[](fg:prev_bg bg:color_green)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:prev_bg bg:color_teal)\
$docker_context\
$conda\
$jobs\
[](fg:prev_bg bg:color_blue)\
$time\
$cmd_duration\
$memory_usage\
[ ](fg:prev_bg)\
$line_break$character"""

palette = 'catppuccin_mocha'
[palettes.catppuccin_mocha]
color_rosewater = "#f5e0dc"
color_flamingo = "#f2cdcd"
color_pink = "#f5c2e7"
color_mauve = "#cba6f7"
color_red = "#f38ba8"
color_maroon = "#eba0ac"
color_peach = "#fab387"
color_yellow = "#f9e2af"
color_green = "#a6e3a1"
color_teal = "#94e2d5"
color_sky = "#89dceb"
color_sapphire = "#74c7ec"
color_blue = "#89b4fa"
color_lavender = "#b4befe"
color_text = "#cdd6f4"
color_subtext1 = "#bac2de"
color_subtext0 = "#a6adc8"
color_overlay2 = "#9399b2"
color_overlay1 = "#7f849c"
color_overlay0 = "#6c7086"
color_surface2 = "#585b70"
color_surface1 = "#45475a"
color_surface0 = "#313244"
color_base = "#1e1e2e"
color_mantle = "#181825"
color_crust = "#11111b"

[username]
show_always = true
style_user = "bg:prev_bg fg:color_surface0"
format = '[  $user@]($style)'

[hostname]
ssh_only = false
style = "fg:prev_fg bg:prev_bg"
format = "[$hostname ]($style)"

[directory]
style = "bg:prev_bg fg:color_surface0"
read_only_style = "fg:color_red bg:prev_bg"
format = "[ $path ]($style)[$read_only]($read_only_style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = "󰌾 "

[git_branch]
symbol = ""
style = "fg:color_surface0 bg:prev_bg"
format = '[ $symbol $branch ]($style)'

[git_commit]
style = "fg:prev_fg bg:prev_bg"
format = "[($tag)]($style) "

[git_status]
style = "fg:color_surface0 bg:prev_bg"
format = '[($all_status$ahead_behind )]($style)'

[nodejs]
symbol = ""
style = "fg:color_surface0 bg:prev_bg"
format = '[ $symbol( $version) ](fg:color_surface0 bg:prev_bg)'

[c]
symbol = " "
style = "fg:color_surface0 bg:prev_bg"
format = '[ $symbol( $version) ]($style)'

[rust]
symbol = ""
style = "fg:color_surface0 bg:prev_bg"
format = '[ $symbol( $version) ]($style)'

[golang]
symbol = ""
style = "fg:color_surface0 bg:prev_bg"
format = '[ $symbol( $version) ]($style)'

[php]
symbol = ""
style = "fg:color_surface0 bg:prev_bg"
format = '[ $symbol( $version) ]($style)'

[java]
symbol = ""
style = "fg:color_surface0 bg:prev_bg"
format = '[ $symbol( $version) ]($style)'

[kotlin]
symbol = ""
style = "fg:color_surface0 bg:prev_bg"
format = '[ $symbol( $version) ]($style)'

[haskell]
symbol = ""
style = "fg:color_surface0 bg:prev_bg"
format = '[ $symbol( $version) ]($style)'

[python]
symbol = ""
style = "fg:color_surface0 bg:prev_bg"
format = '[ $symbol( $version)( $virtualenv) ]($style)'

[docker_context]
symbol = ""
style = "fg:color_surface0 bg:prev_bg"
format = '[ $symbol( $context) ]($style)'

[conda]
symbol = ""
style = "fg:color_surface0 bg:prev_bg"
format = '[ $symbol( $environment) ]($style)'

[jobs]
symbol = "󰆅"
style = "fg:color_surface0 bg:prev_bg"
format = "[ $symbol( $number) ]($style)"

[time]
disabled = false
time_format = "%R"
style = "fg:color_base bg:prev_bg"
format = '[  $time ]($style)'

[cmd_duration]
style = "fg:prev_fg bg:prev_bg"
format = "[ $duration ]($style)"

[memory_usage]
symbol = "󰍛"
style = "fg:bold color_red bg:prev_bg"
format = "[$symbol ${ram}]($style) "
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
